### PR TITLE
Remove unneeded pylab import

### PR DESCRIPTION
**Pull request by jlumpe**
Imports unneeded packages and clutters namespace in module.

### CODE REVIEW

**Comment by epierson9** [comment]
thanks! did you confirm that one can still import and run block ZIFA without this import?

**Comment by jlumpe** [comment]
I haven't written any tests, but `example.py` uses the `block_ZIFA` module and appears to complete successfully.

**Comment by epierson9** [comment]
yeah, but eg see https://github.com/epierson9/ZIFA/blob/master/ZIFA/block_ZIFA.py#L339

**Comment by epierson9** [comment]
i agree it isn't good practice to do "from pylab import *", but ah well...

**Comment by jlumpe** [comment]
Ah, see it. The same thing is in `ZIFA.ZIFA` but no pylab import there.

The reason for this was I actually adapted the model to the Scikit-Learn API for use in pipelines, so I was cleaning up a few things anyway and thought I might as well file a PR.

If you think that would be useful, I could just submit another with this fixed as well as getting rid of some of the code duplication between the two modules.

**Comment by jlumpe** [comment]
Replaced by PR #8.

**Pull request closed without merging**
